import chairOne from "./../../../content/Catalog/ChairOne.png";
import chairTwo from "./../../../content/Catalog/ChairTwo.png";

const CatalogCardInfo = [
  {
    image: chairOne,
    name: "Стул Венеция",
    color: "Белый",
    price: "11.990 руб",
    id: 1,
    type: "Стулья",
  },
  {
    image: chairOne,
    name: "Стул ALLY VBP-206",
    color: "Светло бежевый",
    price: "11.990 руб",
    oldPrice: "17.990 руб",
    id: 2,
    type: "Стулья",
  },
  {
    image: chairTwo,
    name: "Стол Рио",
    color: "Велюрово синий",
    price: "14.000 руб",
    id: 3,
    type: "Столы",
  },
  {
    image: chairOne,
    name: "Стол Виктория",
    color: "Желтый",
    price: "8.500 руб",
    id: 4,
    type: "Столы",
  },
  {
    image: chairOne,
    name: "Кресло Венеция",
    color: "Белый",
    price: "11.990 руб",
    id: 5,
    type: "Кресла",
  },
  {
    image: chairOne,
    name: "Кресло ALLY VBP-206",
    color: "Светло бежевый",
    price: "11.990 руб",
    oldPrice: "17.990 руб",
    id: 6,
    type: "Кресла",
  },
  {
    image: chairTwo,
    name: "Стул Рио",
    color: "Велюрово синий",
    price: "14.000 руб",
    id: 7,
    type: "Стулья",
  },
  {
    image: chairOne,
    name: "Консоли Виктория",
    color: "Желтый",
    price: "8.500 руб",
    id: 8,
    type: "Консоли",
  },
  {
    image: chairOne,
    name: "Стул Венеция",
    color: "Белый",
    price: "11.990 руб",
    id: 9,
    type: "Стулья",
  },
  {
    image: chairOne,
    name: "Стул ALLY VBP-206",
    color: "Светло бежевый",
    price: "11.990 руб",
    oldPrice: "17.990 руб",
    id: 10,
    type: "Стулья",
  },
  {
    image: chairTwo,
    name: "Стол Рио",
    color: "Велюрово синий",
    price: "14.000 руб",
    id: 11,
    type: "Столы",
  },
  {
    image: chairOne,
    name: "Стол Виктория",
    color: "Желтый",
    price: "8.500 руб",
    id: 12,
    type: "Столы",
  },
  {
    image: chairOne,
    name: "Кресло Венеция",
    color: "Белый",
    price: "11.990 руб",
    id: 13,
    type: "Кресла",
  },
  {
    image: chairOne,
    name: "Кресло ALLY VBP-206",
    color: "Светло бежевый",
    price: "11.990 руб",
    oldPrice: "17.990 руб",
    id: 14,
    type: "Кресла",
  },
  {
    image: chairTwo,
    name: "Стул Рио",
    color: "Велюрово синий",
    price: "14.000 руб",
    id: 15,
    type: "Стулья",
  },
  {
    image: chairOne,
    name: "Стул Виктория",
    color: "Желтый",
    price: "8.500 руб",
    id: 16,
    type: "Стулья",
  },
];

export { CatalogCardInfo };
